// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatmessage.proto

package com.laptech.chat.app.server.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.time.LocalDateTime;
import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "messages")
@Data
public class ChatMessage {

  @JsonIgnore
  @Id
  String id;
  String content;
  String receiver;
  String sender;
  @CreatedDate
  LocalDateTime date;
  MessageType type;

  public enum MessageType {
    WHISPER,
    SYSTEM,
    JOIN, LOGOUT, SEND, GET_USERS

  }
}
