// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatmessage.proto

package com.laptech.chat.app.server.model;

import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class ChatMessage {

	String content;
	String receiver;
	String sender;
	MessageType messageType;

	public enum MessageType {
		JOIN, SEND, LOGOUT, GET_USERS;
	}
}
